[project]
name = "lina"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
  "opencv-python>=4.8.0",
  "mediapipe>=0.10.0",
  "numpy>=1.21.0",
  "scipy>=1.7.0",
  "decord>=0.6.0",
  "jax>=0.4.0",
  "jaxlib>=0.4.0",
]
